config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get "tag_search" => "tag_searches#search"
  
  devise_for :users
  # booksにいいねをつける。つまりbooksの下にfavoriteがつく do,end追加
  # 作成、削除のみなのでonly:[:create,:destroy]作成
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    # ネストする
    resources :book_comments, only: [:create,:destroy]
    # resourceはそれ自身のidがわからなくても、関連する他のモデルのidから特定できる場合に使用
    # 今回は一人一回であるためuser_idとbook_idから指定できる
    resource :favorites, only: [:create, :destroy]

  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resources :relationships, only: [:create, :destroy]
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
    get 'relationships/followings' => 'relationships#followings', as: 'followings'
    # member do
    #   get :followings, :followers
    #   # GET /users/id/following
    #   # GET /users/id/followers
    # end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# endなし！
end

# name test1
# pass 111111
# test2
# 222222

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # belongs_toでなくhas many
  # hasumany時は複数形、注意！
  # default:class_name:"favorite" forein_key: "User.id"
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :books, dependent: :destroy

  # @user.active_relationshipsでユーザーのフォローしている(followed)人を呼び出す
  # Relationshipに格納されているfollwer_idとfollowed_idを呼び出す
  has_many :active_relationships,  class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id",dependent: :destroy

  # 見たいのはuserのフォローしているuser達の情報 ↓
  # active_relationshipsで、follower_idを指定して、Relationshipを取得(follwer_id=1)
  # followingsで持ってきたRelationshipに対してfollowedを実行
  # followedはfollowed_id = user_idなのでフォローされているユーザーの情報を呼び出す

  has_many :followings, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローする
  def follow(user_id)
    unless self == user_id
     self.active_relationships.find_or_create_by(followed_id: user_id.to_i, follower_id: self.id)
    end
  end
  # ユーザーのフォローを外す
  def unfollow(user_id)
   active_relationships.find_by(followed_id: user_id).destroy
  end
  # フォロー確認をおこなう
  def following?(user)
   followings.include?(user)
  end

  # 検索メソッド作成
  # def search_for
  #   if search == "parfect_match"
  #     # モデル名.where('カラム名 like ?','検索したい文字列')
  # end

# 検索方法分岐
  def self.search_for(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # 現在のuser_idと投稿者のidが一致していないとはじく
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    # endなし
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    # @user定義なし
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      # render editに戻す
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
  def currect_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td>
          <% unless current_user == user %>
            <% if current_user.following?(user) %>
            <!--routesを見ると user_relationship DELETE /users/:user_id/relationships/:id-->
            <!--つまりuser_id(削除元)、id(削除先)２個のIDを渡さなくてはならない-->
              <%= link_to "フォロー外す", user_relationship_path(user.id, current_user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <!--ここからフォロー、フォロワー-->
  <tr>
    <th>follwes</th>
    <th>
      <%= link_to user.followings.count, user_followings_path(user.id) %>
        <!--< %= user.followings.count %>-->
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user.followers.count, user_followers_path(user.id) %>
        <!--< %= user.followers.count %>-->
    </th>
  </tr>
</table>

<div class ="mb-4">
  <% unless current_user == user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す",user_relationship_path(user.id), method: :delete %>
    <% else %>
      <%= link_to "フォローする",user_relationships_path(user.id), method: :POST %>
    <% end %>
  <% end %>
</div>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <!--title?nameでは？-->
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>