config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get "tag_search" => "tag_searches#search"
  
  devise_for :users
  # booksにいいねをつける。つまりbooksの下にfavoriteがつく do,end追加
  # 作成、削除のみなのでonly:[:create,:destroy]作成
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    # ネストする
    resources :book_comments, only: [:create,:destroy]
    # resourceはそれ自身のidがわからなくても、関連する他のモデルのidから特定できる場合に使用
    # 今回は一人一回であるためuser_idとbook_idから指定できる
    resource :favorites, only: [:create, :destroy]

  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resources :relationships, only: [:create, :destroy]
    get 'relationships/followers' => 'relationships#followers', as: 'followers'
    get 'relationships/followings' => 'relationships#followings', as: 'followings'
    # member do
    #   get :followings, :followers
    #   # GET /users/id/following
    #   # GET /users/id/followers
    # end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# endなし！
end

# name test1
# pass 111111
# test2
# 222222

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  # favoriteで使用するメソッドの定義
  def favorited_by(user)
    # favoritesが存在するか .exists?(カラム名: '田中'のような条件)
    # つまりuser.id を参照してあればtrue
    favorites.exists?(user_id: user.id)
  end
  # presence:true＝nullも空文字もNG
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :tag,presence:true
  # レビュー用バリデーション
   validates :rating, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
  
  scope :sort_rate, ->{order(rating: :desc)}
  scope :sort_new, ->{order(created_at: :desc)}
  scope :sort_old, ->{order(created_at: :asc)}
  
   # 検索メソッド作成
  def self.search_for(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def index
    if params[:rate].present?
      @books = Book.sort_rate
    elsif params[:new].present?
      @books = Book.sort_new
    elsif params[:old].present?
      @books = Book.sort_old
    else
      @books = Book.all
    end
    # @bookにインスタンス作成
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    user_id = @book.user.id
    if user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render 'edit'
    end
  end

  # deleteはmethod
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body,:rating,:tag)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :Tag %>
    <%= f.text_field :tag, class: 'form-control book_tag' %>
  </div>
  
  <% if book.id === nil %>
    <div class="form-group" id="star">
      <%= f.label :rrating %>
      <%= f.hidden_field :rationg, id: :review_star, class:'form-control' %>
    </div>
    <div id="post_raty" class ="mb-3"></div>
    <script>
      $(document).on('turbolinks:load', function() {
         $('#post_raty').empty();
        let elem = document.querySelector('#post_raty');
        let opt = {
          starOn: "<%= asset_path('rating/star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[rating]',
        };
        raty(elem,opt);
      });
    </script>
  <% else %>
    <%= render "books/rating", book: @book %>
  <% end %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td class ="px-0"><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <% if book.tag.nil? %>
          <td></td>
        <% else %>
          <td><%= link_to book.tag, tag_search_path(word: book.tag) %></td>
        <% end %>
        <td id="js-book_favorite_<%= book.id %>">
          <%= render "favorites/nice", book: book %>
        </td>
        <td>コメント数：<%= book.book_comments.count %></td>
        <td class ="px-0"><%= render "books/rating", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_nice.html.erb
   <!--いいね機能部分テンプレート-->
   <!--faivorited_byはbook_modelで指定している-->
  <% if book.favorited_by(current_user) %>
    <!--つまりBook.find(params[:book_id])に user.id = current_user.idが存在しているか？-->
    <!--< %= if Book.find(params[:book_id]).favorites.exists?(bookカラム[user_id]: user.id) %>-->
    <%= link_to book_favorites_path(book), method: :delete do %>
      ♥<%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post do %>
      ♡<%= book.favorites.count %>
    <% end %>
  <% end %>

app/views/books/_rating.html.erb
<div id="rate_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  $('#rate_<%= book.id %>').empty();
  let raty_<%= book.id %> = document.querySelector('#rate_<%= book.id %>');
  let option_<%= book.id %> = {
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    readOnly: true,
    score: <%= book.rating %>,
  };
  raty(raty_<%= book.id %> ,option_<%= book.id %>);
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class ="d-flex justify-content-center mb-2">
 <div class ="px-4"><%= render 'layouts/search' %></div>
 <div class ="px-4"><%= render 'layouts/tag_search' %></div>
</div>
<div class='container px-5 px-sm-0'>
  <!--新規投稿失敗時にerror.messageを表示-->
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <p><%= link_to '新しい順', books_path(new:"new")%> | 
      <%= link_to '古い順', books_path(old:"old")%> | 
      <%= link_to '評価の高い順', books_path(rate:"rate")%></p>
      <%= render partial: 'index', locals: { books: @books } %>
      <!--# < %= render 'index', books: @books,book: @book %>-->
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container p-0 mx-auto'>
   <%= render 'layouts/errors', obj: @book_comment %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <!--user: @userはここで@user = @book.userにすればいい-->
      <%= render 'users/info', user: @book.user%>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id="js-book_favorite_<%= @book.id %>">
            <%= render 'favorites/nice', book: @book %>
          </td>
          <td>コメント数：<%= @book.book_comments.count %></td>
          <td class ="px-0"><%= render "books/rating", book: @book %></td>
          
          <% if @book.user.id == current_user.id %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', book_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <div id ="js-book_comments_<%= @book.id %>">
        <%= render "book_comments/index", book: @book %>
      </div>
        <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
      <!--<table class ="table table-borderless m-0">-->
      <!--  < % @book.book_comments.each do |book_comment| %>-->
      <!--    <tr>-->
              <!--これだとpost指定でコメントが保存できる。但しコメント保存後sizeの部分がgiven2でerrorを起こす-->
              <!--< %= image_tag book_comment.user.profile_image(50,50)%><br>-->
      <!--      <td style= "width:10%">< %= link_to(book_comment.user) do %>-->
      <!--        < %= image_tag book_comment.user.get_profile_image, size:"50x50" %><br>-->
      <!--        < %= book_comment.user.name %>-->
      <!--        < % end %>-->
      <!--      </td>-->

      <!--      <td>< %= book_comment.comment %></td>-->
      <!--      < % if book_comment.user.id == current_user.id %>-->
      <!--        <td>< %= link_to 'Destroy', book_book_comment_path(book_comment.book,book_comment), method: :delete, class: "btn btn-sm btn-danger"%></td>-->
      <!--      < % end %>-->
      <!--    </tr>-->
      <!--  < % end %>-->
      <!--</table>-->
      <!--< %= form_with model:[@book, @book_comment] do |f| %>-->
      <!--  <table class = "table table-borderless">-->
      <!--    <tr>-->
          <!--メソッド指定なしだとgetになって遅れていなかった。-->
          <!--が、get_prolire_imageのエラーを修正後postだと送れなくなる。なぜ？？-->
          <!--< %= form_with model:[@book, @book_comment],method: :post do |f| %>-->
      <!--      <td>-->
      <!--        < %= f.text_area :comment , class: 'form-control book_comment'%><br>-->
      <!--        < %= f.submit "送信" %>-->
      <!--      </td>-->
      <!--    </tr>-->
      <!--  </table>-->
      <!--< % end %>-->
    </div>
  </div>
</div>